version: '3.4'

services:
  grafana:
    container_name: grafana
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3400:3000
    volumes:
      - ./dist:/var/lib/grafana/plugins/sophicautomation-nerve-datasource
      - ./provisioning:/etc/grafana/provisioning
